// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfoSetOperationOperation int32

const (
	UserInfoSetOperation_set   UserInfoSetOperationOperation = 0
	UserInfoSetOperation_clear UserInfoSetOperationOperation = 1
)

var UserInfoSetOperationOperation_name = map[int32]string{
	0: "set",
	1: "clear",
}

var UserInfoSetOperationOperation_value = map[string]int32{
	"set":   0,
	"clear": 1,
}

func (x UserInfoSetOperationOperation) String() string {
	return proto.EnumName(UserInfoSetOperationOperation_name, int32(x))
}

func (UserInfoSetOperationOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{4, 0}
}

type UserInfoSetOperationField int32

const (
	UserInfoSetOperation_nickname    UserInfoSetOperationField = 0
	UserInfoSetOperation_description UserInfoSetOperationField = 1
)

var UserInfoSetOperationField_name = map[int32]string{
	0: "nickname",
	1: "description",
}

var UserInfoSetOperationField_value = map[string]int32{
	"nickname":    0,
	"description": 1,
}

func (x UserInfoSetOperationField) String() string {
	return proto.EnumName(UserInfoSetOperationField_name, int32(x))
}

func (UserInfoSetOperationField) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{4, 1}
}

type LoginResultDataOrErr int32

const (
	LoginResult_isData LoginResultDataOrErr = 0
	LoginResult_isErr  LoginResultDataOrErr = 1
)

var LoginResultDataOrErr_name = map[int32]string{
	0: "isData",
	1: "isErr",
}

var LoginResultDataOrErr_value = map[string]int32{
	"isData": 0,
	"isErr":  1,
}

func (x LoginResultDataOrErr) String() string {
	return proto.EnumName(LoginResultDataOrErr_name, int32(x))
}

func (LoginResultDataOrErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{11, 0}
}

type SignupResultDataOrErr int32

const (
	SignupResult_isData SignupResultDataOrErr = 0
	SignupResult_isErr  SignupResultDataOrErr = 1
)

var SignupResultDataOrErr_name = map[int32]string{
	0: "isData",
	1: "isErr",
}

var SignupResultDataOrErr_value = map[string]int32{
	"isData": 0,
	"isErr":  1,
}

func (x SignupResultDataOrErr) String() string {
	return proto.EnumName(SignupResultDataOrErr_name, int32(x))
}

func (SignupResultDataOrErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{12, 0}
}

type GetUserInfoResultDataOrErr int32

const (
	GetUserInfoResult_isData GetUserInfoResultDataOrErr = 0
	GetUserInfoResult_isErr  GetUserInfoResultDataOrErr = 1
)

var GetUserInfoResultDataOrErr_name = map[int32]string{
	0: "isData",
	1: "isErr",
}

var GetUserInfoResultDataOrErr_value = map[string]int32{
	"isData": 0,
	"isErr":  1,
}

func (x GetUserInfoResultDataOrErr) String() string {
	return proto.EnumName(GetUserInfoResultDataOrErr_name, int32(x))
}

func (GetUserInfoResultDataOrErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{13, 0}
}

type SetUserInfoResultDataOrErr int32

const (
	SetUserInfoResult_isData SetUserInfoResultDataOrErr = 0
	SetUserInfoResult_isErr  SetUserInfoResultDataOrErr = 1
)

var SetUserInfoResultDataOrErr_name = map[int32]string{
	0: "isData",
	1: "isErr",
}

var SetUserInfoResultDataOrErr_value = map[string]int32{
	"isData": 0,
	"isErr":  1,
}

func (x SetUserInfoResultDataOrErr) String() string {
	return proto.EnumName(SetUserInfoResultDataOrErr_name, int32(x))
}

func (SetUserInfoResultDataOrErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{14, 0}
}

type GetOthersInfoResultDataOrErr int32

const (
	GetOthersInfoResult_isData GetOthersInfoResultDataOrErr = 0
	GetOthersInfoResult_isErr  GetOthersInfoResultDataOrErr = 1
)

var GetOthersInfoResultDataOrErr_name = map[int32]string{
	0: "isData",
	1: "isErr",
}

var GetOthersInfoResultDataOrErr_value = map[string]int32{
	"isData": 0,
	"isErr":  1,
}

func (x GetOthersInfoResultDataOrErr) String() string {
	return proto.EnumName(GetOthersInfoResultDataOrErr_name, int32(x))
}

func (GetOthersInfoResultDataOrErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{15, 0}
}

type Username struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Username) Reset()         { *m = Username{} }
func (m *Username) String() string { return proto.CompactTextString(m) }
func (*Username) ProtoMessage()    {}
func (*Username) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *Username) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Username.Unmarshal(m, b)
}
func (m *Username) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Username.Marshal(b, m, deterministic)
}
func (m *Username) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Username.Merge(m, src)
}
func (m *Username) XXX_Size() int {
	return xxx_messageInfo_Username.Size(m)
}
func (m *Username) XXX_DiscardUnknown() {
	xxx_messageInfo_Username.DiscardUnknown(m)
}

var xxx_messageInfo_Username proto.InternalMessageInfo

func (m *Username) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Password struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Password) Reset()         { *m = Password{} }
func (m *Password) String() string { return proto.CompactTextString(m) }
func (*Password) ProtoMessage()    {}
func (*Password) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *Password) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Password.Unmarshal(m, b)
}
func (m *Password) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Password.Marshal(b, m, deterministic)
}
func (m *Password) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Password.Merge(m, src)
}
func (m *Password) XXX_Size() int {
	return xxx_messageInfo_Password.Size(m)
}
func (m *Password) XXX_DiscardUnknown() {
	xxx_messageInfo_Password.DiscardUnknown(m)
}

var xxx_messageInfo_Password proto.InternalMessageInfo

func (m *Password) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type UserInfoSetOperation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoSetOperation) Reset()         { *m = UserInfoSetOperation{} }
func (m *UserInfoSetOperation) String() string { return proto.CompactTextString(m) }
func (*UserInfoSetOperation) ProtoMessage()    {}
func (*UserInfoSetOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{4}
}

func (m *UserInfoSetOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoSetOperation.Unmarshal(m, b)
}
func (m *UserInfoSetOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoSetOperation.Marshal(b, m, deterministic)
}
func (m *UserInfoSetOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoSetOperation.Merge(m, src)
}
func (m *UserInfoSetOperation) XXX_Size() int {
	return xxx_messageInfo_UserInfoSetOperation.Size(m)
}
func (m *UserInfoSetOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoSetOperation.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoSetOperation proto.InternalMessageInfo

type LoginArgs struct {
	Username             *Username `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             *Password `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginArgs) Reset()         { *m = LoginArgs{} }
func (m *LoginArgs) String() string { return proto.CompactTextString(m) }
func (*LoginArgs) ProtoMessage()    {}
func (*LoginArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{5}
}

func (m *LoginArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginArgs.Unmarshal(m, b)
}
func (m *LoginArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginArgs.Marshal(b, m, deterministic)
}
func (m *LoginArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginArgs.Merge(m, src)
}
func (m *LoginArgs) XXX_Size() int {
	return xxx_messageInfo_LoginArgs.Size(m)
}
func (m *LoginArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginArgs.DiscardUnknown(m)
}

var xxx_messageInfo_LoginArgs proto.InternalMessageInfo

func (m *LoginArgs) GetUsername() *Username {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *LoginArgs) GetPassword() *Password {
	if m != nil {
		return m.Password
	}
	return nil
}

type SignupArgs struct {
	Username             *Username `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             *Password `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignupArgs) Reset()         { *m = SignupArgs{} }
func (m *SignupArgs) String() string { return proto.CompactTextString(m) }
func (*SignupArgs) ProtoMessage()    {}
func (*SignupArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{6}
}

func (m *SignupArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupArgs.Unmarshal(m, b)
}
func (m *SignupArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupArgs.Marshal(b, m, deterministic)
}
func (m *SignupArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupArgs.Merge(m, src)
}
func (m *SignupArgs) XXX_Size() int {
	return xxx_messageInfo_SignupArgs.Size(m)
}
func (m *SignupArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupArgs.DiscardUnknown(m)
}

var xxx_messageInfo_SignupArgs proto.InternalMessageInfo

func (m *SignupArgs) GetUsername() *Username {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *SignupArgs) GetPassword() *Password {
	if m != nil {
		return m.Password
	}
	return nil
}

type SetUserInfoArgs struct {
	Token                 *Token                  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserInfoSetOperations []*UserInfoSetOperation `protobuf:"bytes,2,rep,name=userInfoSetOperations,proto3" json:"userInfoSetOperations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *SetUserInfoArgs) Reset()         { *m = SetUserInfoArgs{} }
func (m *SetUserInfoArgs) String() string { return proto.CompactTextString(m) }
func (*SetUserInfoArgs) ProtoMessage()    {}
func (*SetUserInfoArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{7}
}

func (m *SetUserInfoArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserInfoArgs.Unmarshal(m, b)
}
func (m *SetUserInfoArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserInfoArgs.Marshal(b, m, deterministic)
}
func (m *SetUserInfoArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserInfoArgs.Merge(m, src)
}
func (m *SetUserInfoArgs) XXX_Size() int {
	return xxx_messageInfo_SetUserInfoArgs.Size(m)
}
func (m *SetUserInfoArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserInfoArgs.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserInfoArgs proto.InternalMessageInfo

func (m *SetUserInfoArgs) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *SetUserInfoArgs) GetUserInfoSetOperations() []*UserInfoSetOperation {
	if m != nil {
		return m.UserInfoSetOperations
	}
	return nil
}

type GetOthersInfoArgs struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOthersInfoArgs) Reset()         { *m = GetOthersInfoArgs{} }
func (m *GetOthersInfoArgs) String() string { return proto.CompactTextString(m) }
func (*GetOthersInfoArgs) ProtoMessage()    {}
func (*GetOthersInfoArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{8}
}

func (m *GetOthersInfoArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOthersInfoArgs.Unmarshal(m, b)
}
func (m *GetOthersInfoArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOthersInfoArgs.Marshal(b, m, deterministic)
}
func (m *GetOthersInfoArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOthersInfoArgs.Merge(m, src)
}
func (m *GetOthersInfoArgs) XXX_Size() int {
	return xxx_messageInfo_GetOthersInfoArgs.Size(m)
}
func (m *GetOthersInfoArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOthersInfoArgs.DiscardUnknown(m)
}

var xxx_messageInfo_GetOthersInfoArgs proto.InternalMessageInfo

func (m *GetOthersInfoArgs) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetOthersInfoArgs) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{9}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Err struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Err) Reset()         { *m = Err{} }
func (m *Err) String() string { return proto.CompactTextString(m) }
func (*Err) ProtoMessage()    {}
func (*Err) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{10}
}

func (m *Err) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Err.Unmarshal(m, b)
}
func (m *Err) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Err.Marshal(b, m, deterministic)
}
func (m *Err) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Err.Merge(m, src)
}
func (m *Err) XXX_Size() int {
	return xxx_messageInfo_Err.Size(m)
}
func (m *Err) XXX_DiscardUnknown() {
	xxx_messageInfo_Err.DiscardUnknown(m)
}

var xxx_messageInfo_Err proto.InternalMessageInfo

func (m *Err) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Err) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LoginResult struct {
	Token                *Token   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Err                  *Err     `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResult) Reset()         { *m = LoginResult{} }
func (m *LoginResult) String() string { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()    {}
func (*LoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{11}
}

func (m *LoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResult.Unmarshal(m, b)
}
func (m *LoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResult.Marshal(b, m, deterministic)
}
func (m *LoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResult.Merge(m, src)
}
func (m *LoginResult) XXX_Size() int {
	return xxx_messageInfo_LoginResult.Size(m)
}
func (m *LoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResult proto.InternalMessageInfo

func (m *LoginResult) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *LoginResult) GetErr() *Err {
	if m != nil {
		return m.Err
	}
	return nil
}

type SignupResult struct {
	Token                *Token   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Err                  *Err     `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupResult) Reset()         { *m = SignupResult{} }
func (m *SignupResult) String() string { return proto.CompactTextString(m) }
func (*SignupResult) ProtoMessage()    {}
func (*SignupResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{12}
}

func (m *SignupResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResult.Unmarshal(m, b)
}
func (m *SignupResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResult.Marshal(b, m, deterministic)
}
func (m *SignupResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResult.Merge(m, src)
}
func (m *SignupResult) XXX_Size() int {
	return xxx_messageInfo_SignupResult.Size(m)
}
func (m *SignupResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResult.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResult proto.InternalMessageInfo

func (m *SignupResult) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *SignupResult) GetErr() *Err {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetUserInfoResult struct {
	UserInfo             *UserInfo `protobuf:"bytes,2,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	Err                  *Err      `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserInfoResult) Reset()         { *m = GetUserInfoResult{} }
func (m *GetUserInfoResult) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoResult) ProtoMessage()    {}
func (*GetUserInfoResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{13}
}

func (m *GetUserInfoResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoResult.Unmarshal(m, b)
}
func (m *GetUserInfoResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoResult.Marshal(b, m, deterministic)
}
func (m *GetUserInfoResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoResult.Merge(m, src)
}
func (m *GetUserInfoResult) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoResult.Size(m)
}
func (m *GetUserInfoResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoResult proto.InternalMessageInfo

func (m *GetUserInfoResult) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *GetUserInfoResult) GetErr() *Err {
	if m != nil {
		return m.Err
	}
	return nil
}

type SetUserInfoResult struct {
	Empty                *Empty   `protobuf:"bytes,2,opt,name=empty,proto3" json:"empty,omitempty"`
	Err                  *Err     `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserInfoResult) Reset()         { *m = SetUserInfoResult{} }
func (m *SetUserInfoResult) String() string { return proto.CompactTextString(m) }
func (*SetUserInfoResult) ProtoMessage()    {}
func (*SetUserInfoResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{14}
}

func (m *SetUserInfoResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserInfoResult.Unmarshal(m, b)
}
func (m *SetUserInfoResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserInfoResult.Marshal(b, m, deterministic)
}
func (m *SetUserInfoResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserInfoResult.Merge(m, src)
}
func (m *SetUserInfoResult) XXX_Size() int {
	return xxx_messageInfo_SetUserInfoResult.Size(m)
}
func (m *SetUserInfoResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserInfoResult.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserInfoResult proto.InternalMessageInfo

func (m *SetUserInfoResult) GetEmpty() *Empty {
	if m != nil {
		return m.Empty
	}
	return nil
}

func (m *SetUserInfoResult) GetErr() *Err {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetOthersInfoResult struct {
	UserInfo             *UserInfo `protobuf:"bytes,2,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	Err                  *Err      `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetOthersInfoResult) Reset()         { *m = GetOthersInfoResult{} }
func (m *GetOthersInfoResult) String() string { return proto.CompactTextString(m) }
func (*GetOthersInfoResult) ProtoMessage()    {}
func (*GetOthersInfoResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{15}
}

func (m *GetOthersInfoResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOthersInfoResult.Unmarshal(m, b)
}
func (m *GetOthersInfoResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOthersInfoResult.Marshal(b, m, deterministic)
}
func (m *GetOthersInfoResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOthersInfoResult.Merge(m, src)
}
func (m *GetOthersInfoResult) XXX_Size() int {
	return xxx_messageInfo_GetOthersInfoResult.Size(m)
}
func (m *GetOthersInfoResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOthersInfoResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetOthersInfoResult proto.InternalMessageInfo

func (m *GetOthersInfoResult) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *GetOthersInfoResult) GetErr() *Err {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterEnum("helloworld.UserInfoSetOperationOperation", UserInfoSetOperationOperation_name, UserInfoSetOperationOperation_value)
	proto.RegisterEnum("helloworld.UserInfoSetOperationField", UserInfoSetOperationField_name, UserInfoSetOperationField_value)
	proto.RegisterEnum("helloworld.LoginResultDataOrErr", LoginResultDataOrErr_name, LoginResultDataOrErr_value)
	proto.RegisterEnum("helloworld.SignupResultDataOrErr", SignupResultDataOrErr_name, SignupResultDataOrErr_value)
	proto.RegisterEnum("helloworld.GetUserInfoResultDataOrErr", GetUserInfoResultDataOrErr_name, GetUserInfoResultDataOrErr_value)
	proto.RegisterEnum("helloworld.SetUserInfoResultDataOrErr", SetUserInfoResultDataOrErr_name, SetUserInfoResultDataOrErr_value)
	proto.RegisterEnum("helloworld.GetOthersInfoResultDataOrErr", GetOthersInfoResultDataOrErr_name, GetOthersInfoResultDataOrErr_value)
	proto.RegisterType((*Username)(nil), "helloworld.Username")
	proto.RegisterType((*Password)(nil), "helloworld.Password")
	proto.RegisterType((*Token)(nil), "helloworld.Token")
	proto.RegisterType((*UserInfo)(nil), "helloworld.UserInfo")
	proto.RegisterType((*UserInfoSetOperation)(nil), "helloworld.UserInfoSetOperation")
	proto.RegisterType((*LoginArgs)(nil), "helloworld.LoginArgs")
	proto.RegisterType((*SignupArgs)(nil), "helloworld.SignupArgs")
	proto.RegisterType((*SetUserInfoArgs)(nil), "helloworld.SetUserInfoArgs")
	proto.RegisterType((*GetOthersInfoArgs)(nil), "helloworld.GetOthersInfoArgs")
	proto.RegisterType((*Empty)(nil), "helloworld.Empty")
	proto.RegisterType((*Err)(nil), "helloworld.Err")
	proto.RegisterType((*LoginResult)(nil), "helloworld.LoginResult")
	proto.RegisterType((*SignupResult)(nil), "helloworld.SignupResult")
	proto.RegisterType((*GetUserInfoResult)(nil), "helloworld.GetUserInfoResult")
	proto.RegisterType((*SetUserInfoResult)(nil), "helloworld.SetUserInfoResult")
	proto.RegisterType((*GetOthersInfoResult)(nil), "helloworld.GetOthersInfoResult")
}

func init() {
	proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2)
}

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 580 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xdf, 0x6b, 0xd3, 0x50,
	0x14, 0x6e, 0x12, 0xb3, 0xad, 0x27, 0x9b, 0x4b, 0x8f, 0x9d, 0x96, 0xca, 0x58, 0xbd, 0x0f, 0xdb,
	0x40, 0x18, 0x52, 0x41, 0x10, 0x7c, 0x19, 0x58, 0x86, 0x38, 0xa8, 0xa6, 0xea, 0xab, 0xc4, 0xe6,
	0xae, 0x0b, 0x4b, 0x73, 0xc3, 0xbd, 0xb7, 0x0c, 0x1f, 0xf4, 0xc5, 0x57, 0xf1, 0xc1, 0xff, 0xd1,
	0xff, 0x43, 0xee, 0x4d, 0x6e, 0x9a, 0x34, 0x15, 0x11, 0x86, 0x7b, 0x3b, 0xe7, 0xe4, 0x3b, 0x3f,
	0xf8, 0xbe, 0x8f, 0x1b, 0xf0, 0x2f, 0x69, 0x92, 0xb0, 0x6b, 0xc6, 0x93, 0xe8, 0x24, 0xe3, 0x4c,
	0x32, 0x84, 0x65, 0x85, 0x1c, 0xc2, 0xd6, 0x7b, 0x41, 0x79, 0x1a, 0xce, 0x29, 0xf6, 0x61, 0x6b,
	0x51, 0xc4, 0x3d, 0x6b, 0x60, 0x1d, 0xb7, 0x83, 0x32, 0x57, 0xb8, 0x37, 0xa1, 0x10, 0xd7, 0x8c,
	0x47, 0x0a, 0x97, 0x15, 0xb1, 0xc1, 0x99, 0x9c, 0xec, 0x83, 0xfb, 0x8e, 0x5d, 0xd1, 0x14, 0xbb,
	0xe0, 0x4a, 0x15, 0x14, 0x88, 0x3c, 0x21, 0xcf, 0xf2, 0x75, 0xaf, 0xd2, 0x0b, 0x86, 0x77, 0xc1,
	0x8e, 0xcd, 0x00, 0x3b, 0xd6, 0x63, 0xd3, 0x78, 0x7a, 0xa5, 0xd7, 0xdb, 0xf9, 0x58, 0x93, 0x93,
	0x8f, 0xd0, 0x35, 0x7d, 0x13, 0x2a, 0xc7, 0x19, 0xe5, 0xa1, 0x8c, 0x59, 0x4a, 0x0e, 0xa0, 0xcd,
	0x4c, 0x82, 0x9b, 0xe0, 0x08, 0x2a, 0xfd, 0x16, 0xb6, 0xc1, 0x9d, 0x26, 0x34, 0xe4, 0xbe, 0x45,
	0x0e, 0xc1, 0xbd, 0x88, 0x69, 0x12, 0xe1, 0xf6, 0x72, 0xba, 0xdf, 0xc2, 0x5d, 0xf0, 0x22, 0x2a,
	0xa6, 0x3c, 0xce, 0x54, 0xa7, 0x6f, 0x11, 0x06, 0xed, 0x73, 0x36, 0x8b, 0xd3, 0x53, 0x3e, 0x13,
	0xf8, 0x64, 0x85, 0x08, 0x6f, 0xd8, 0x3d, 0xa9, 0xb0, 0x68, 0x08, 0x5b, 0xd2, 0xa3, 0x3a, 0x4a,
	0x4a, 0xec, 0x66, 0x87, 0xa1, 0xae, 0x42, 0x54, 0x06, 0x30, 0x89, 0x67, 0xe9, 0x22, 0xfb, 0x6f,
	0x1b, 0x7f, 0x5a, 0xb0, 0x3b, 0xa1, 0xd2, 0xf0, 0xa8, 0xf7, 0x1e, 0x55, 0x55, 0xf2, 0x86, 0x9d,
	0xea, 0x08, 0xad, 0x63, 0x21, 0x1c, 0x7e, 0x80, 0xbd, 0xc5, 0x1a, 0x01, 0x44, 0xcf, 0x1e, 0x38,
	0xc7, 0xde, 0x70, 0xb0, 0x7a, 0xed, 0x2a, 0x30, 0x58, 0xdf, 0x4e, 0xce, 0xa1, 0x73, 0x46, 0xe5,
	0x58, 0x5e, 0x52, 0x2e, 0xfe, 0xfd, 0xaa, 0xdc, 0x42, 0xb6, 0xb1, 0x10, 0xd9, 0x04, 0x77, 0x34,
	0xcf, 0xe4, 0x67, 0xf2, 0x18, 0x9c, 0x11, 0xe7, 0x88, 0x70, 0x67, 0xca, 0xa2, 0x9c, 0xd2, 0x9d,
	0x40, 0xc7, 0xe8, 0x83, 0x33, 0x17, 0xb3, 0xa2, 0x49, 0x85, 0xe4, 0x0b, 0x78, 0x5a, 0xfb, 0x80,
	0x8a, 0x45, 0x22, 0x97, 0xdb, 0xed, 0xbf, 0x6c, 0x7f, 0x04, 0x0e, 0xe5, 0xbc, 0xe7, 0x68, 0xd8,
	0x6e, 0x15, 0x36, 0xe2, 0x3c, 0x50, 0xdf, 0x08, 0x81, 0x76, 0x14, 0xca, 0x70, 0xcc, 0xd5, 0x35,
	0x00, 0x1b, 0xb1, 0x78, 0x19, 0xca, 0x30, 0xb7, 0x68, 0x2c, 0x46, 0x5c, 0x59, 0xf4, 0x2b, 0x6c,
	0xe7, 0x4e, 0xb8, 0xa5, 0xfd, 0xdf, 0x2d, 0xad, 0x81, 0x51, 0xad, 0xb8, 0xa2, 0x70, 0xa4, 0xaa,
	0xac, 0xf3, 0x57, 0x89, 0x2e, 0x51, 0x37, 0x75, 0xce, 0x37, 0x0b, 0x3a, 0x93, 0xc6, 0x39, 0x47,
	0xe0, 0x52, 0xa5, 0xec, 0x3a, 0x52, 0xb4, 0xe4, 0x41, 0xfe, 0xfd, 0xa6, 0xae, 0xf8, 0x61, 0xc1,
	0xbd, 0x9a, 0x31, 0x6f, 0x99, 0x96, 0xe1, 0x2f, 0x1b, 0x36, 0xcf, 0x38, 0xa5, 0x92, 0x72, 0x7c,
	0x0e, 0xae, 0x36, 0x2c, 0xee, 0x55, 0xc7, 0x95, 0xef, 0x57, 0xff, 0x41, 0xa3, 0x9c, 0x5f, 0x4f,
	0x5a, 0xf8, 0x02, 0x36, 0x72, 0xb3, 0xe1, 0xfd, 0x2a, 0x68, 0xf9, 0x14, 0xf5, 0x7b, 0xcd, 0x7a,
	0xd9, 0x7d, 0x0a, 0x5e, 0xc5, 0x29, 0xd8, 0xb4, 0x66, 0x7f, 0xbf, 0x5a, 0x6a, 0xb8, 0x8a, 0xb4,
	0xf0, 0x35, 0x78, 0x15, 0x75, 0xf1, 0x61, 0x6d, 0x5b, 0xfd, 0x75, 0xaa, 0x0f, 0x9b, 0xac, 0x19,
	0xf6, 0x16, 0x76, 0x6a, 0x22, 0xe1, 0xea, 0xfa, 0xfa, 0xc3, 0xd2, 0x3f, 0xf8, 0xe3, 0x67, 0x33,
	0xf2, 0xd3, 0x86, 0xfe, 0x47, 0x3e, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x46, 0x23, 0xb9, 0xf6,
	0x37, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	Login(ctx context.Context, in *LoginArgs, opts ...grpc.CallOption) (*LoginResult, error)
	Signup(ctx context.Context, in *SignupArgs, opts ...grpc.CallOption) (*SignupResult, error)
	GetUserInfo(ctx context.Context, in *Token, opts ...grpc.CallOption) (*GetUserInfoResult, error)
	SetUserInfo(ctx context.Context, in *SetUserInfoArgs, opts ...grpc.CallOption) (*SetUserInfoResult, error)
	GetOthersInfo(ctx context.Context, in *GetOthersInfoArgs, opts ...grpc.CallOption) (*GetOthersInfoResult, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Login(ctx context.Context, in *LoginArgs, opts ...grpc.CallOption) (*LoginResult, error) {
	out := new(LoginResult)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) Signup(ctx context.Context, in *SignupArgs, opts ...grpc.CallOption) (*SignupResult, error) {
	out := new(SignupResult)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetUserInfo(ctx context.Context, in *Token, opts ...grpc.CallOption) (*GetUserInfoResult, error) {
	out := new(GetUserInfoResult)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SetUserInfo(ctx context.Context, in *SetUserInfoArgs, opts ...grpc.CallOption) (*SetUserInfoResult, error) {
	out := new(SetUserInfoResult)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetOthersInfo(ctx context.Context, in *GetOthersInfoArgs, opts ...grpc.CallOption) (*GetOthersInfoResult, error) {
	out := new(GetOthersInfoResult)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/GetOthersInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	Login(context.Context, *LoginArgs) (*LoginResult, error)
	Signup(context.Context, *SignupArgs) (*SignupResult, error)
	GetUserInfo(context.Context, *Token) (*GetUserInfoResult, error)
	SetUserInfo(context.Context, *SetUserInfoArgs) (*SetUserInfoResult, error)
	GetOthersInfo(context.Context, *GetOthersInfoArgs) (*GetOthersInfoResult, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) Login(ctx context.Context, req *LoginArgs) (*LoginResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedGreeterServer) Signup(ctx context.Context, req *SignupArgs) (*SignupResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedGreeterServer) GetUserInfo(ctx context.Context, req *Token) (*GetUserInfoResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedGreeterServer) SetUserInfo(ctx context.Context, req *SetUserInfoArgs) (*SetUserInfoResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserInfo not implemented")
}
func (*UnimplementedGreeterServer) GetOthersInfo(ctx context.Context, req *GetOthersInfoArgs) (*GetOthersInfoResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOthersInfo not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Login(ctx, req.(*LoginArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Signup(ctx, req.(*SignupArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetUserInfo(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserInfoArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SetUserInfo(ctx, req.(*SetUserInfoArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetOthersInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOthersInfoArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetOthersInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/GetOthersInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetOthersInfo(ctx, req.(*GetOthersInfoArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Greeter_Login_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _Greeter_Signup_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Greeter_GetUserInfo_Handler,
		},
		{
			MethodName: "SetUserInfo",
			Handler:    _Greeter_SetUserInfo_Handler,
		},
		{
			MethodName: "GetOthersInfo",
			Handler:    _Greeter_GetOthersInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
